### ISSUE TITLE
Add camera entities for picture download feature

### ISSUE THREAD

**Issue by Thesola10** [pcourbin/imaprotect#136]
**Is your feature request related to a problem? Please describe.**
Not particularly, just a nice-to-have. It would help add a dynamic background to Lovelace cards, or complete an automation to notify when the alarm is triggered

**Describe the solution you'd like**
This integration would add a camera entity for each camera listed on the IMA dashboard. I'm not exactly sure how HASS polls for cameras, but IMA Protect does provide an option to download a picture from a given camera

**Describe alternatives you've considered**
Cobbling a script together would be a hassle and mostly redundant to this integration.

**Comment by pcourbin** [comment]
Merci beaucoup pour la contribution, l'ajout de la caméra et la correction sur le login !
Je n'ai pas été disponible ces derniers temps... et je ne vais peut être pas conserver cette alarme à l'avenir. 
Si vous souhaitez être ajouté en contributeur pour continuer à maintenir ces intégration/package, n'hésitez pas à me le dire surtout :wink:
